"""fix Users table(once more...)

Revision ID: 44b2b4e672a7
Revises: 4967f7fa4afa
Create Date: 2024-04-05 21:45:23.316744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b2b4e672a7'
down_revision: Union[str, None] = '4967f7fa4afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('offers', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
