"""Fix Users Table

Revision ID: 4967f7fa4afa
Revises: a8f5da198249
Create Date: 2024-04-02 16:02:14.664581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4967f7fa4afa'
down_revision: Union[str, None] = 'a8f5da198249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offers', ['photos'])
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['password'])
    op.drop_column('users', 'active_offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_offers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'offers', type_='unique')
    # ### end Alembic commands ###
