"""init migration

Revision ID: 5d3851bc0a4b
Revises: 
Create Date: 2024-02-16 23:37:56.668962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d3851bc0a4b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("location", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("photos", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.PrimaryKeyConstraint("uuid", "photos"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("offers", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("active_offers", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", "offers"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("offers")
    # ### end Alembic commands ###
