"""Add description

Revision ID: 9952c0c071e2
Revises: d7574ffb0cd5
Create Date: 2024-02-19 19:37:26.840792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9952c0c071e2'
down_revision: Union[str, None] = 'd7574ffb0cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('description', sa.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'description')
    # ### end Alembic commands ###
