"""Fix author column

Revision ID: a8f5da198249
Revises: 2449ddb27865
Create Date: 2024-02-29 21:02:05.703228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f5da198249'
down_revision: Union[str, None] = '2449ddb27865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'offers',
        sa.Column('author', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    )
    op.drop_column('offers', 'author_id')
    op.add_column('users', sa.Column('account_id', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.drop_column('users', 'account_id')
    op.add_column(
        'offers',
        sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_column('offers', 'author')
    # ### end Alembic commands ###
